### ISSUE TITLE
Статика отдается без кеширования

### ISSUE THREAD

**Issue by Medvezhopok** [idlesign/pythonz#10]
Статический контент отдается без кеширования, 
варианты решения:
1) уйти за cloudflare
2) настроить кеширование всего из папки static/

**Comment by idlesign** [comment]
Уходить не будем, а над кешированием подумаем.

**Comment by idlesign** [comment]
Кеш включен для статики из static и media. Местами введено кеширование в шаблонах.
Закрываю.
