### ISSUE TITLE
не корректные ссылки на сторонние файлы если открывать через https://

### ISSUE THREAD

**Issue by Medvezhopok** [idlesign/pythonz#12]
есть ссылки на сторонние ресурсы через http, если загржать сайт через https:// файлы не загрузятся или будут сообщения что чать ресурсов грузится не безопастно

**Comment by idlesign** [comment]
Спасибо. 
Необходимо оформить отдельным запросом на слияние.

**Comment by idlesign** [comment]
Реализовано. Закрываю.
