### ISSUE TITLE
Изменить отображение справочника

### ISSUE THREAD

**Issue by WarmongeR1** [idlesign/pythonz#3]
(обсуждали мысль по изменению отображения справочника,
была мысль сделать одну страницу на один модуль, сбоку добавить меню)

**Comment by idlesign** [comment]
- [x] Перенести связанные материалы в боковую панель
- [ ] Правильно строить навигационную цепочку (хлебные крошки) до страницы справочника
- [ ] Добавить карту справочника (иерархию)

**Comment by idlesign** [comment]
Теперь иерархия материалов в справочнике дублируется древом сайта.

Верно строится и работает навигационная цепочка, в правую панель отнесены соседние  а также материалы в данной секции.

Вывести иерархией как в оригинальной документации теперь проблемы нет, не понятно только где это действительно нужно.

Как должна выглядеть "одна страница на один модуль" тоже не понятно. Если есть какой-то мелкий модуль, который вообще имеет смысл оформить на одной странице то этому ничего не мешает сейчас - оформляется новая статья справочника, весь модуль описывается в теле.

**Comment by idlesign** [comment]
Навигационная цепочка, правая панель и поиск работают, поэтому пока считаем что сделанных изменений достаточно и оставляем как есть. 
Закрываю.
