### ISSUE TITLE
Не работает счетчик комментариев Disqus

### ISSUE THREAD

**Issue by rusnasonov** [idlesign/pythonz#41]
<img width="1136" alt="python - - 2018-12-28 14-40-53" src="https://user-images.githubusercontent.com/4026379/50507167-d96e9100-0aae-11e9-8bb7-ebe69e98796b.png">

Оставил комментарий, счетчик не увеличился. Страницу перезагружал.

http://pythonz.net/articles/204/

**Comment by idlesign** [comment]
Сейчас комментарии дискуса остались только в обсуждениях (например, https://pythonz.net/discussions/60/) в дальнейшем, вероятно, совсем будут отключены. 
Счётчик вроде работает. Закрываю задачу.
