### ISSUE TITLE
Кнопки в профиле пользователя

### ISSUE THREAD

**Issue by AnkoII** [idlesign/pythonz#46]
Может стоит как-то оформить кнопки Профиль, Настройки и Выход, чтобы они стояли не слитно. Либо вообще убрать, они все равно есть в сворачивающемся списке.
![pythonz_butt](https://user-images.githubusercontent.com/43611092/56847026-e83f4600-68de-11e9-9d70-05796ce29ca5.PNG)

**Comment by idlesign** [comment]
Спасибо.
Да, пожалуй. Похоже после перехода на бутстрап 4 съехало.
Убрать будет сложнее (там отображаются и другие вложенные разделы), а вот отступов добавить — это недорого.
