### ISSUE TITLE
Выпадающее меню профиля

### ISSUE THREAD

**Issue by AnkoII** [idlesign/pythonz#49]
![pythonz](https://user-images.githubusercontent.com/43611092/61995562-dcf0e780-b092-11e9-9d46-dc8ca40b2b55.PNG)
Надо бы сдвинуть выпадающее окошко в левую сторону, а то при нажатии появляется возможность двигать сайт влево-вправо

**Comment by idlesign** [comment]
Спасибо за информацию.

Вижу, что такого можно добиться, если блок с именем узкий. Например, если там будет имя и фамилия, то отрисуется так:

![submenu](https://user-images.githubusercontent.com/145644/62001054-f173c500-b110-11e9-882d-59c68e529b4a.png)

Позиционирование меню вероятно поможет: https://getbootstrap.com/docs/4.3/components/dropdowns/#menu-alignment

**Comment by AnkoII** [comment]
Я так понял, это уже в sitetree нужно новый шаблон добавлять, типа menu_bootstrap4_dropdown_right.html?

**Comment by idlesign** [comment]
Да, можно так, а можно css как-то поковырять попробовать.

**Comment by idlesign** [comment]
Исправлено в #51
