### ISSUE TITLE
Подумать над футером и фоном

### ISSUE THREAD

**Issue by AnkoII** [idlesign/pythonz#50]
Наверное стоит сделать, чтобы футер всегда был снизу. А еще что-то сделать с фоном, потому-что это выглядит так себе
![pz](https://user-images.githubusercontent.com/43611092/62009073-9f0fc400-b163-11e9-94f3-531aad5c00bc.PNG)

**Comment by idlesign** [comment]
Да, пожалуй что-то можно придумать.
От градиента, наверное, придётся избавиться.

**Comment by idlesign** [comment]
Вроде решилось. Закрываю.
