### ISSUE TITLE
Реализовать страницу с наиболее часто запрашиваемыми справочными материалами

### ISSUE THREAD

**Issue by idlesign** [idlesign/pythonz#6]
Сейчас оповещение о том, что пользователь чего-то не нашел в справочнике отсылается почтой. Неплохо бы сделать старицу с рейтингом таких запросов, чтобы знать какие разделы справки формировать в первую очередь.

**Comment by Medvezhopok** [comment]
Сначала надо сделать сбор статистики, а потом отображение на основе статистики

**Comment by idlesign** [comment]
Разумеется.
