### ISSUE TITLE
Странное поведение сводок

### ISSUE THREAD

**Issue by idlesign** [idlesign/pythonz#60]
Из Телеграм-канала:
```
antuan, [21.01.20 21:03]
[В ответ на робот pythonz.net]
последние несколько месяцев в сводках летят июнские новости :(
```

**Comment by idlesign** [comment]
если сравнить http://pythonz.net/articles/288/ и 
http://pythonz.net/articles/289/, то видно, что они разные.
видимо барахлит именно разбор рассылок.

**Comment by aCLr** [comment]
https://mail.python.org не открывается из РФ, через тор ок. Кажется, для фетчеров нужно использовать прокси.

**Comment by idlesign** [comment]
Хорошо, проверим доступность сервера с архивом рассылок с нового хостинга.

Однако это не объясняет, почему `последние несколько месяцев в сводках летят июнские новости`. Хостинг в РФ начался лишь на прошлой неделе.

**Comment by aCLr** [comment]
Могу предположить, что [поэтому](https://github.com/idlesign/pythonz/blob/master/pythonz/apps/models.py#L267)

**Comment by idlesign** [comment]
Эти источники с июня не обновляются — переехали на mailman 3.
Нужно будет попробовать забирать оттуда: https://mail.python.org/archives/

**Comment by idlesign** [comment]
REST API HyperKitty не поддерживает ограничение вывода тем, фильтрацию тоже.
https://mail.python.org/archives/api/lists/
Рассылки давние, и при запросе к API происходит попытка показать все темы, их сервер надолго задумывается и обрывает связь.
Похоже на данном этапе получать информацию мы можем только через разбор страницы.

**Comment by idlesign** [comment]
Подрихтовал. Теперь будет выглядеть так: https://pythonz.net/articles/291/
Закрываю.
