### ISSUE TITLE
Нет оглавления в справочнике

### ISSUE THREAD

**Issue by suhanoves** [idlesign/pythonz#71]
В справочнике нет оглавления справа ни под одним браузером. Блокировщики рекламы выключены.

**Comment by idlesign** [comment]
А о каком оглавлении речь?

**Comment by suhanoves** [comment]
Игорь, в на [стартовой странице справочника](https://pythonz.net/references/named/python/) есть такой абзац:
«Справочник построен иерархически. Воспользуйтесь оглавлением, расположенным в правой колонке, чтобы переместиться к интересующему вас разделу»
Но оглавления я не увидел справа, и ниже был комментарий аналогичный, поэтому решил открыть issue.

**Comment by idlesign** [comment]
А, теперь понял.

Дело в том, что когда-то оглавление действительно было справа. Но потом оно разрасталось и стало неудобно им пользоваться, поэтому оно переехало под текст статей.

Спасибо за наводку, исправил.
Закрываю. Если ещё отыщутся нестыковки, можете смело создавать задачи. Помимо этого, некоторые страницы на сайте зарегистрированные пользователи могут править самостоятельно.
