### ISSUE TITLE
принудительный редирект на https

### ISSUE THREAD

**Issue by andrewkoltsov** [idlesign/pythonz#9]
сейчас сайт открывается по http но есть и https версия, сделать принудительный редирект на https

**Comment by idlesign** [comment]
Пока не вижу смысла: сейчас используется не слишком мощная виртуалка, поэтому доп. нагрузка ей не нужна, в будущем - подумаем. Оставляю открытым, чтобы не забыть.

**Comment by idlesign** [comment]
Ходят слухи, что поисковики стали предпочитать сайты с HTTPS, поэтому включаем перенаправление по умолчанию.
Готово.
